baseURL = "https://blog.paketo.io"
languageCode = "en-us"
title = "Paketo Buildpacks | Blog"

[params.authors]
  kvedurmudi = "Kashyap Vedurmudi"
  rmoran = "Ryan Moran"
  feckhardt = "Forest Eckhardt"
