baseURL = "https://blog.paketo.io"
languageCode = "en-us"
title = "Paketo Buildpacks | Blog"
enableEmoji = true

[params.authors]
  dmikusa = "Daniel Mikusa"
  dosullivan = "David O'Sullivan"
  ecasey = "Emily Casey"
  fgallinajones = "Frankie Gallina-Jones"
  joshuatcasey = "Joshua Casey"
  kevinortega = "Kevin Ortega"
  kvedurmudi = "Kashyap Vedurmudi"
  rmoran = "Ryan Moran"
  swigmore = "Sophie Wigmore"
  despejo = "David Espejo"
  anthonydahanne = "Anthony Dahanne"
  mhdawson = "Michael Dawson"
  pacostas = "Costas Papastathis"
  bmcdonald = "Brynley McDonald"
