---
name: Update Tools

on:
  schedule:
  - cron: '42 19 * * 0'  # weekly on Sunday at 19:42 UTC
  workflow_dispatch: {}

concurrency: tools_update

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Checkout Branch
      uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: automation/tools/update

    - name: Fetch Latest Hugo
      id: latest-hugo
      uses: paketo-buildpacks/github-config/actions/tools/latest@main
      with:
        token: ${{ github.token }}
        repo: gohugoio/hugo

    - name: Update scripts/tools.json
      env:
        HUGO_VERSION: ${{ steps.latest-hugo.outputs.version }}
      run: |
        jq --null-input \
           --sort-keys \
           --arg hugo "${HUGO_VERSION}" \
           '{ hugo: $hugo }' > ./scripts/.util/tools.json

    - name: Commit
      id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "Updating tools"
        pathspec: "."

    - name: Push Branch
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: automation/tools/update

    - name: Open Pull Request
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ github.token }}
        title: "Updates tools"
        branch: automation/tools/update

  failure:
    name: Alert on Failure
    runs-on: ubuntu-24.04
    needs: [update]
    if: ${{ always() && needs.update.result == 'failure' }}
    steps:
    - name: File Failure Alert Issue
      uses: paketo-buildpacks/github-config/actions/issue/file@main
      with:
        token: ${{ github.token }}
        repo: ${{ github.repository }}
        label: "failure:update-tools"
        comment_if_exists: true
        issue_title: "Failure: Update Tools workflow"
        issue_body: |
          Update Tools workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
        comment_body: |
           Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
